name: Build GitHub Action
description: Convert typescript to javascript and push to remote as orphan
author: Hyperbola

inputs:
  github-token:
    description: github token
    required: true
  dist-dir:
    description: directory whose contents are to be pushed
    required: false
    default: ./dist
  dist-branch:
    description: target branch to push the build
    required: false
    default: release
  user-name:
    description: commit user for the build
    required: false
    default: deploy-bot
  user-email:
    description: commit email for the build
    required: false
    default: deploy-bot@hyperbola.me
  commit-message: 
    description: commit message for the build
    required: false
    default: build

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Setup nodejs v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build project
      shell: /usr/bin/bash -e {0}
      run: yarn install --frozen-lockfile && yarn build
    - name: Get version
      id: version
      uses: martinbeentjes/npm-get-version-action@main
    - name: Push to release branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.dist-dir }}
        publish_branch: ${{ inputs.dist-branch }}
        commit_message: ${{ inputs.commit-message }}
        user_name: ${{ inputs.user-name }}
        user_email: ${{ inputs.user-email }}
        force_orphan: false
        disable_nojekyll: true
    - name: Bump version
      shell: /usr/bin/bash -e {0}
      run: |
        version=${{ steps.version.outputs.current-version }}
        # source version tag
        git tag -f src-$version main
        # version tag
        git fetch origin tmp
        git tag -f $version origin/tmp
        # minor version tag
        minor_version=${version%.*}
        git tag -f $minor_version $version
        # major version tag
        major_version=${version%%.*}
        git tag -f $major_version $version
        # push tags
        git push -f origin src-$version $version $minor_version $major_version
