name: Action of Action
description: Convert a TS action to JS and push to a release branch
author: hyperbola

inputs:
  github-token:
    description: github token
    required: false
    default: ${{ github.token }}
  dist-dir:
    description: directory whose contents are to be pushed
    required: false
    default: ./dist
  dist-branch:
    description: target branch to push the build
    required: false
    default: release
  user-name:
    description: commit user for the build
    required: false
    default: bot
  user-email:
    description: commit email for the build
    required: false
    default: bot@hyperbola.me

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Setup nodejs v16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm and project dependencies
      uses: pnpm/action-setup@v2
      with:
        run_install: true
    - name: Build project
      shell: /usr/bin/bash -e {0}
      run: pnpm build
    - name: Get version
      id: version
      uses: wdzeng/version@v1
      with:
        prefix: v
    - name: Push to release branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ${{ inputs.dist-dir }}
        publish_branch: ${{ inputs.dist-branch }}
        full_commit_message: build ${{ github.sha }} (${{ steps.version.outputs.version }})
        user_name: ${{ inputs.user-name }}
        user_email: ${{ inputs.user-email }}
        force_orphan: false
        disable_nojekyll: true
    - name: Bump version
      shell: /usr/bin/bash -e {0}
      env:
        VER_MAJ: ${{ steps.version.outputs.major }}
        VER_MIN: ${{ steps.version.outputs.minor }}
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        # source version tag
        git tag -f src-$VERSION main
        # version tag
        git fetch origin ${{ inputs.dist-branch }}
        git tag -f $VERSION origin/${{ inputs.dist-branch }}
        # minor version tag
        git tag -f $VER_MIN origin/${{ inputs.dist-branch }}
        # major version tag
        git tag -f $VER_MAJ origin/${{ inputs.dist-branch }}
        # push tags
        git push -f origin src-$VERSION $VERSION $VER_MIN $VER_MAJ
